spring:
  application:
    name: dbauth
  profiles:
    active: dev,db
---
spring:
  config:
    activate:
      on-profile: dev
    import: optional:file:.env.dev[.properties]
  thymeleaf:
    cache: false
  security:
    user:
      name: myuser
      password: mypassword
